// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFN3bcUkyZ3Xs6lYRKlg7uTYYmIS1XRfY',
    appId: '1:941758040083:web:e037c6ab95b2a9bca057e6',
    messagingSenderId: '941758040083',
    projectId: 'fir-39cfd',
    authDomain: 'fir-39cfd.firebaseapp.com',
    storageBucket: 'fir-39cfd.firebasestorage.app',
    measurementId: 'G-BT1BWFTZ92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAASGtdwDbm5uEbc1_11u2-yE4ghYBhlY',
    appId: '1:941758040083:android:2b01ee9498b5a673a057e6',
    messagingSenderId: '941758040083',
    projectId: 'fir-39cfd',
    storageBucket: 'fir-39cfd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6BvsaQvUbHxsYHpHkOhGwLWA1TF9CHJ8',
    appId: '1:941758040083:ios:08f759be5ea24c28a057e6',
    messagingSenderId: '941758040083',
    projectId: 'fir-39cfd',
    storageBucket: 'fir-39cfd.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6BvsaQvUbHxsYHpHkOhGwLWA1TF9CHJ8',
    appId: '1:941758040083:ios:08f759be5ea24c28a057e6',
    messagingSenderId: '941758040083',
    projectId: 'fir-39cfd',
    storageBucket: 'fir-39cfd.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFN3bcUkyZ3Xs6lYRKlg7uTYYmIS1XRfY',
    appId: '1:941758040083:web:4359930a4114940ca057e6',
    messagingSenderId: '941758040083',
    projectId: 'fir-39cfd',
    authDomain: 'fir-39cfd.firebaseapp.com',
    storageBucket: 'fir-39cfd.firebasestorage.app',
    measurementId: 'G-JPQM4C8D2T',
  );
}
